# -*- coding: utf-8 -*-
"""TFintroipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1RbhgfUJvDbYZkU_aq28U9R2zActSYNpe

<a href="https://colab.research.google.com/github/lmoroney/dlaicourse/blob/master/TensorFlow%20In%20Practice/Course%203%20-%20NLP/Course%203%20-%20Week%202%20-%20Lesson%201.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

-----------------------------------------------------------
-----------------------------------------------------------
Create a tokenizer fitted to my csv file
"""

#imports colab library ie access to drive
from google.colab import drive 
#requests auth to colab file
drive.mount('/content/drive', force_remount = True)

# Commented out IPython magic to ensure Python compatibility.
#specify directory path (note that csv file has to be in the same directory as colab file)

# %cd /content/drive/'My Drive'/'Research'/

import pandas as pd 

columns = ["fid", "dgname", "ptname", "fsen"]
datastore = pd.read_csv("SampleCSV.csv", names = columns)

#since the first element is label, slice it
fid = datastore['fid'][1:]
dgname = datastore['dgname'][1:]
ptname = datastore['ptname'][1:]
fsen = datastore['fsen'][1:]

#check data
print(dgname)

from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokenizer = Tokenizer(oov_token="<OOV>")

#only want to fit the drug name
#tokenizer.fit_on_texts(fid)
tokenizer.fit_on_texts(dgname)
#tokenizer.fit_on_texts(ptname)
#tokenizer.fit_on_texts(fsen)

word_index = tokenizer.word_index

print(len(word_index))
print(word_index)

#tokenizer contains only the drug names, fit only drug names to sentences
#this way, tokenizer will detect drug names
seq = tokenizer.texts_to_sequences(fsen)
padded = pad_sequences(seq, padding='post')

print(padded[0])
print(padded.shape)

print("\nSequences = " , seq)
print("\n")


search = {}
keys = []
vals = []

#find which sentences have drug names
for i in range(0, len(seq)):
  for j in range(0, len(seq[i])):
    if seq[i][j] != 1:
      search[i] = seq[i][j]

for i in word_index:
      keys.append(i)
      vals.append(word_index[i])


for i in search:
  print(fid[i + 1], "has info on", keys[vals.index(search[i])])


print("\nPadded Sequences:")
print(padded)